name: Game
version: 2.0.0
main: GamePlugin\Main
api: 4.0.0
author: MiddleDev
depend:
- BedrockEconomy

commands:
  game:
    permission: middle.game
    description: "Игра камень, ножницы, бумага"
permissions:
  middle.game:
    default: true
