author: vk.com/middle1221

#Это показатель максимальной ставки в игре
MaxAmountMoney: 2001
#Это показатель минимальной ставки в игре
MinAmountMoney: 0
#Это строка включит проверку нажатия на любой блок для вызова комманды /game. По умолчанию выключено
FuncInteractOff: true

#Это уже сами настройки этой фуннкции(если она включена)
FuncInteract:
  #Позиция блока, которая будет отслеживаться(можно узнать через Debugging)
  positions:
    posX: 153
    posY: 68
    posZ: -64
  #Это id нужного блока(можно узнать через Debugging)
  Block:
    id: 68
  #Эта уже можно изменить комманду, которая выполняется после тапа на блок(без /)
  Command: game
  #Эта штука упрастит вам изменение координат и id блока
  Debugging: 
    #Уровень 0 = функция выключена, Уровень 1 = писаться будет только позиция нажатого блока(x, y, z), Уровень 2 = на нём будет так же писаться и id нажатого вами блока
    Level: 0